######################################################################
#
# File name : TB_MODULE_wave.do
# Created on: Tue Nov 21 21:39:43 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
