######################################################################
#
# File name : TB_MODULE_compile.do
# Created on: Tue Nov 21 21:46:36 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom -64 -93 -work xil_defaultlib  \
"../../../../tut_vhdlcomb01_a4.srcs/sources_1/imports/hdl/module.vhd" \
"../../../../tut_vhdlcomb01_a4.srcs/sim_1/imports/hdl/tb_module.vhd" \


