######################################################################
#
# File name : TB_MODULE_wave.do
# Created on: Tue Nov 21 22:52:42 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
