set_property SRC_FILE_INFO {cfile:/media/sf_sync/DD/josef/U2/tut_vhdlcomb02_a3/tut_vhdlcomb02_a3.srcs/constrs_1/imports/impl/Arty_ArtyA735_ArtyA7100_Master.xdc rfile:../../../tut_vhdlcomb02_a3.srcs/constrs_1/imports/impl/Arty_ArtyA735_ArtyA7100_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D9    IOSTANDARD LVCMOS33 } [get_ports { btn[0]}]; #IO_L6N_T0_VREF_16 Sch=btn[0]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C9    IOSTANDARD LVCMOS33 } [get_ports { btn[1]}]; #IO_L11P_T1_SRCC_16 Sch=btn[1]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T11   IOSTANDARD LVCMOS33 } [get_ports { segments[0]  }]; #IO_L19P_T3_A10_D26_14 Sch=ck_io[3]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { segments[4] }]; #IO_L7P_T1_D09_14 Sch=ck_io[39]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P18   IOSTANDARD LVCMOS33 } [get_ports { segments[5] }]; #IO_L9N_T1_DQS_D13_14 Sch=ck_io[40]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N17   IOSTANDARD LVCMOS33 } [get_ports { segments[1] }]; #IO_L9P_T1_DQS_14 Sch=ck_io[41]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C7    IOSTANDARD LVCMOS33 } [get_ports { segments[6] }]; #IO_L4N_T0_35 Sch=ck_a[2]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D5    IOSTANDARD LVCMOS33 } [get_ports { segments[3] }]; #IO_L11P_T1_SRCC_35 Sch=ck_a[5]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M17   IOSTANDARD LVCMOS33 } [get_ports { segments[2] }]; #IO_L10N_T1_D15_14 Sch=ck_ioa
