######################################################################
#
# File name : module_simulate.do
# Created on: Mon Nov 20 19:54:53 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L secureip -lib xil_defaultlib xil_defaultlib.module

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {module_wave.do}

view wave
view structure
view signals

do {module.udo}

run 1000ns
