######################################################################
#
# File name : module_wave.do
# Created on: Mon Nov 20 19:54:53 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
