######################################################################
#
# File name : TB_MODULE_wave.do
# Created on: Fri Nov 03 14:39:47 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
