set_property SRC_FILE_INFO {cfile:/media/sf_1data/sync/sync/DD/josef/work/fpga/simplebsp/simplebsp.srcs/constrs_1/imports/simplebsp_src/Arty_ArtyA735_ArtyA7100_Master.xdc rfile:../../../simplebsp.srcs/constrs_1/imports/simplebsp_src/Arty_ArtyA735_ArtyA7100_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { LED0 }]; #IO_L24N_T3_35 Sch=led[4]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J5    IOSTANDARD LVCMOS33 } [get_ports { LED1 }]; #IO_25_35 Sch=led[5]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D9    IOSTANDARD LVCMOS33 } [get_ports { BTN0 }]; #IO_L6N_T0_VREF_16 Sch=btn[0]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C9    IOSTANDARD LVCMOS33 } [get_ports { BTN1 }]; #IO_L11P_T1_SRCC_16 Sch=btn[1]
