######################################################################
#
# File name : TB_MODULE_wave.do
# Created on: Mon Nov 20 16:56:28 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
