######################################################################
#
# File name : TB_SEVENSEG_compile.do
# Created on: Mon Nov 20 20:03:38 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom -64 -93 -work xil_defaultlib  \
"../../../../tut_vhdlcomb02.srcs/sim_1/imports/hdl/tb_module.vhd" \


