######################################################################
#
# File name : TB_SEVENSEG_wave.do
# Created on: Mon Nov 20 20:03:39 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
