######################################################################
#
# File name : TB_MODULE_wave.do
# Created on: Sat Nov 04 13:48:52 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
