######################################################################
#
# File name : TB_SEVENSEG_wave.do
# Created on: Sat Nov 04 13:02:28 CET 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
